/*
 * Note - this file is _not_ autogenerated.  You are supposed to _remove_
 * (not comment out, but remove or change to undef) lines responsible for
 * features you do not want.
 */

#define WITH_READLINE
#define WITH_GLIB

